routes/web.php
            Route::get('getManagement', ['as'=>'getManagement', 'uses' => 'HomeController@getManagement']);
            Route::get('getVacantList', ['as'=>'getVacantList', 'uses' => 'HomeController@getVacantList']);

            Route::get('getPropertyReleaseInvoice', ['as'=>'getPropertyReleaseInvoice', 'uses' => 'HomeController@getPropertyReleaseInvoice']);
            Route::get('release-invoice', ['as'=>'release_invoice', 'uses' => 'HomeController@releaseInvoice']);
            Route::get('release-contract', ['as'=>'release_contract', 'uses' => 'HomeController@releaseContract']);
            Route::get('getInsuranceReleaseLogs', ['as'=>'getInsuranceReleaseLogs', 'uses' => 'HomeController@getInsuranceReleaseLogs']);
            Route::get('getMahnungTenant', ['as'=>'getMahnungTenant', 'uses' => 'HomeController@getMahnungTenant']);
            Route::get('getMahnungAmount', ['as'=>'getMahnungAmount', 'uses' => 'HomeController@getMahnungAmount']);

            Route::get('getassetmanagerproperty', ['as'=>'getassetmanagerproperty', 'uses' => 'HomeController@getassetmanagerproperty']);

            Route::get('mailchimp', ['as'=>'mailchimp', 'uses' => 'HomeController@mailchimp']);
            Route::get('monthyearmanager', ['as'=>'monthyearmanager', 'uses' => 'HomeController@monthYearManager']);
            Route::get('monthyearassetmanager', ['as'=>'monthyearassetmanager', 'uses' => 'HomeController@monthYearAssetmanager']);


            Route::post('delete-pdf', 'PropertiesController@deletePdf')->name('delete_property_pdf');
            Route::post('add_new_bank', 'PropertiesController@addNewBank')->name('add_new_bank');
            Route::post('add_new_banken', 'PropertiesController@addNewBanken')->name('add_new_banken');
            Route::post('update_bank', 'PropertiesController@updateBank')->name('update_bank');
            Route::get('get_bank/{id}', 'PropertiesController@getBank')->name('get_bank');

            Route::get('getbanklist', ['as'=>'getbanklist', 'uses' => 'PropertiesController@getbanklist']);
            Route::get('getBankFinanceOffers', ['as'=>'getBankFinanceOffers', 'uses' => 'PropertiesController@getBankFinanceOffers']);
            Route::get('getAllBankMailLogsOfProperty/', ['as'=>'getAllBankMailLogsOfProperty', 'uses' => 'PropertiesController@getAllBankMailLogsOfProperty']);
            Route::get('getstatusloi', ['as'=>'getstatusloi', 'uses' => 'PropertiesController@getstatusloi']);
            Route::get('getStatusLoiByUserId', ['as'=>'getStatusLoiByUserId', 'uses' => 'PropertiesController@getStatusLoiByUserId']);
            Route::get('getstatusloidahboard/{month}', ['as'=>'getstatusloidahboard', 'uses' => 'DashboardController@getstatusloi']);
            Route::get('getStatusLoiByUserIdDashboard', ['as'=>'getStatusLoiByUserIdDashboard', 'uses' => 'DashboardController@getStatusLoiByUserId']);
            Route::get('export_properties', ['as'=>'export_properties', 'uses' => 'PropertiesController@export_properties']);
            // Route::get('add-new-vacant', ['as'=>'add-new-vacant', 'uses' => 'PropertiesController@addNewVacant']);

            Route::get('delete_new_vacant', ['as'=>'delete_new_vacant', 'uses' => 'PropertiesController@delete_new_vacant']);




            Route::resource('/', 'DashboardController');
            Route::get('/external', 'DashboardController@external')->name('external');

            Route::get('/getstatustable', 'DashboardController@getstatustable')->name('getstatustable');
            Route::get('/export_property_pdf', 'DashboardController@export_property_pdf')->name('export_property_pdf');
            Route::get('/searchproperty', 'DashboardController@searchproperty')->name('searchproperty');

            Route::get('/getstatustabledashboard', 'DashboardController@getstatustabledashboard')->name('getstatustabledashboard');

            //
            Route::post('/property_management/add', 'PropertyManagementController@add')->name('property_management.add');
            Route::post('/property_management/update_row', 'PropertyManagementController@update_row')->name('property_management.update');

            Route::get('/assetmanagement', 'AssetManagementController@index')->name('assetmanagement');
            Route::get('/assetmanagement-optimized', 'AssetManagementController@assetManagementOptimized')->name('assetmanagement_optimized');
            Route::get('/getRentCompare', 'AssetManagementController@getRentCompare')->name('getRentCompare');
            Route::get('/getRentCompareList', 'AssetManagementController@getRentCompareList')->name('getRentCompareList');
            Route::get('/assetmanagement/chart', 'ChartController@index')->name('assetmanagement.chart');
            Route::resource('/users', 'UserController');
            Route::resource('/properties', 'PropertiesController');
            Route::resource('/calendar', 'CalendarController');

            Route::get('/property/{id}/comments', 'PropertyCommentsController@show')->name('propertycomments.show');
            Route::get('/property/comments', 'PropertyCommentsController@_show')->name('propertycomments._show');

            Route::get('dashboard/get-retnal-activity', 'HomeController@getRentalActivity')->name('get_retnal_activity');
        });
        Route::get('add-new-vacant', ['as'=>'add-new-vacant', 'uses' => 'PropertiesController@addNewVacant'])->middleware('auth');
        Route::post('/changeempfehlungdetails', 'PropertiesController@changeempfehlungdetails')->name('changeempfehlungdetails')->middleware('auth');

        Route::post('/assetmanagement', 'AssetManagementController@index')->name('assetmanagementfilter');
        Route::post('property/saveEmpfehlungFile','PropertiesController@saveEmpfehlungFile')->name('saveEmpfehlungFile');
        Route::post('property/saveMieterlisteFile','PropertiesController@saveMieterlisteFile')->name('saveMieterlisteFile');
        Route::get('property/delete-tenant-payment-file/{id}','PropertiesController@deleteTenantPaymentFile')->name('delete_tenant_payment_file');

        Route::post('save_sheet', 'AdsController@saveSheet')->name('save_sheet');
        Route::get('create_soll/{id}/{bank_id}', 'AdsController@saveSoll')->name('create_soll');

        Route::post('save_gsheet', 'AdsController@saveGSheet')->name('save_gsheet');





//Heat Map
        Route::get('/heatmap', 'HomeController@heatmap')->name('heatmap');

        Route::get('/home', 'HomeController@index')->name('home');
        Route::post('/property/create-comment','PropertyCommentsController@create')->name('create_propertycomment');
        Route::get('/property/{id}/edit-comment','PropertyCommentsController@edit')->name('edit_propertycomment');
        Route::post('/property/update-comment','PropertyCommentsController@update_comment')->name('update_propertycomment');

        Route::post('/dashboard/change-comment','HomeController@changeComment')->name('change-comment');

        Route::post('upload-einkauf-file','HomeController@uploadBuyFiles')->name('upload-einkauf-file');

        Route::post('upload-bank-file','HomeController@uploadBankFiles')->name('upload-bank-file');





        Route::post('/property/edit_comment_iframe/{id}','PropertyCommentsController@edit_comment_show_iframe')->name('edit_comment_show_iframe');


        Route::post('/verkauf-item/update/{id}/{type}','PropertiesController@update_verkauf_item')->name('update_verkauf_item');
        Route::post('/verkauf/update/{id}','PropertiesController@update_verkauf')->name('update_verkauf');

        Route::get('/property/set_as_standard/{orignal_prop}/{pid}', 'PropertiesController@set_as_standard');

        Route::post('/einkauf-item/update/{id}/{type}','PropertiesController@update_einkauf_item')->name('update_einkauf_item');
        Route::post('/einkauf/update/{id}','PropertiesController@update_einkauf')->name('update_einkauf');



        Route::post('property/comment-date', array(
            'as' => 'update.comment.date',
            'uses' => 'PropertyCommentsController@updateCommentDate'));

        Route::post('/properties/{id}/update_property','PropertiesController@update_property')->name('update_property');
        Route::get('/property-comparison','PropertiesController@comparsion')->name('property_comparison');
        Route::post('/property-comparison','PropertiesController@comparsion')->name('property_comparison');
        Route::post('/calendar/create_calendar','CalendarController@create_calendar')->name('create_calendar');
        Route::post('/calendar/edit_event','CalendarController@edit_event')->name('edit_event');
        Route::get('/users/{id}/edit-profile','UserController@getProfile')->name('edit-profile');
        Route::post('/users/{id}/edit-profile','UserController@postProfile')->name('edit-profile');
        Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
        Route::get('/change-password', 'UserController@getChangePassword')->name('change-password');
        Route::post('/change-password', 'UserController@postChangePassword')->name('change-password');
        Route::get('/login-history', 'UserController@loginHistory')->name('login_history');
        Route::get('/login-history-data', 'UserController@loginHistoryData')->name('login_history_data');
        Route::get('/export-history-data', 'UserController@exportHistoryData')->name('export_history_data');

        Route::get('/property-history', 'UserController@propertyHistory')->name('property_history');
        Route::get('/property-history-data', 'UserController@propertyHistoryData')->name('property_history_data');

        Route::post('/change-property-status', 'PropertiesController@changeStatus')->name('properties.change_status');
        Route::get('/user-activities', 'UserController@showUserActivities')->middleware('auth')->name('user-activities');
        Route::post('/user-confirm-password', 'UserController@confirmPassword')->middleware('auth')->name('confirm_password');

resources/views/dashboard/optimized/tables/comments.blade.php
<div class="row">
   <div class="col-sm-12" style="margin-top: 25px; padding: 0 5px;">
      <div class="white-box">
         {{-- <h3 class="box-title m-b-0">Kommentare</h3> --}}
         {{-- <p class="text-muted m-b-30">&nbsp;</p> --}}
         <div class="row">
            <div class="col-sm-6" style="height:440px; overflow-y: scroll;">
               @foreach($comments as $comment)
               <div class="d-flex flex-row comment-row mt-0 mb-0">
                  <div class="p-2">
                     <img src="{{(config('upload.avatar_path').$comment->user->image)}}" alt="user" width="40" class="rounded-circle" style="border-radius: 50%;">
                  </div>
                  <div class="comment-text w-100">
                     <h5 class="font-normal mb-1">{{$comment->user->name}}</h5>
                     <span class="text-muted mr-2 font-12">
                     {{ show_datetime_format($comment->created_at) }}
                     </span>
                     <span class="hidden badge @if($comment->status == 'Steht aus') badge-info @endif @if($comment->status == 'Akzeptiert') badge-success @endif @if($comment->status == 'Abgelehnt') badge-danger @endif badge-rounded text-uppercase font-medium">{{ $comment->status }}</span>
                     <p class="mb-2 d-block font-14 text-muted font-light mt-3" style="">
                        <a  href="{{route('properties.show',['property'=>$comment->property_id])}}?tab=comment_tab">
                        {{ $comment->name_of_property }} :
                        </a>
                        <a href="{{route('properties.show',['property'=>$comment->property_id])}}?tab=comment_tab">
                        {!! $comment->comment !!}
                        </a>
                     </p>
                     @if($comment->pdf_file)
                     <a href="{{ asset('pdf_upload/'.$comment->pdf_file) }}"  target="_blank" style="font-size: 20px;"><i class="fa fa-file-pdf-o"></i></a><br/>
                     @endif
                     <hr>
                     {{-- 
                     <div class="mt-3">
                        <a href="javacript:void(0)" class="btn btn btn-rounded btn-outline-success mr-2 btn-sm"><i class="ti-check mr-1"></i>Akzeptieren</a>
                        <a href="javacript:void(0)" class="btn-rounded btn btn-outline-danger btn-sm"><i class="ti-close mr-1"></i> Ablehnen</a>
                     </div>
                     --}}
                  </div>
               </div>
               @endforeach
            </div>
            <div class="col-sm-6">
               <div class="table-responsive">
                  <table class="table table-striped" id="comment-table">
                     <tbody>
                        @foreach($ccomments as $comment)
                        <tr>
                           <td>
                              <a  href="{{route('properties.show',['property'=>$comment->property_id])}}?tab=comment_tab">
                              {{ $comment->name_of_property }} :
                              </a>
                           </td>
                           <td>{{$comment->name}}</td>
                           <td>
                              <a class="comment-detail" href="javacript:void(0)" data-id="{{$comment->id}}">
                              @if($comment->type==1)
                              Mahnung
                              @elseif($comment->type==2)
                              Gerichtliches Mahnverfahren
                              @elseif($comment->type==3)
                              Ratenzahlung/Kündigung
                              @endif
                              </a>
                           </td>
                           <td>{{show_datetime_format($comment->created_at)}}</td>
                        </tr>
                        @endforeach
                        @if(1==2)
                        <tr>
                           <td>Mahnung</td>
                           <td><input type="checkbox" @if(isset($ccomments[0]['status']) && $ccomments[0]['status']) checked @endif></td>
                           <td>@if(isset($ccomments[0]['comment'])){{$ccomments[0]['comment']}}@endif
                              <br>
                              @if(isset($ccomments[0]['files']) && $ccomments[0]['files'])
                              <?php
                                 $ar = json_decode($ccomments[0]['files'],true)
                                 ?>
                              @foreach($ar as $list)
                              <a href="{{ asset('pdf_upload/'.$list) }}"  target="_blank" style="font-size: 20px;"><i class="fa fa-file-pdf-o"></i></a>
                              @endforeach
                              @endif
                           </td>
                        </tr>
                        <tr>
                           <td>Gerichtliches Mahnverfahren </td>
                           <td><input type="checkbox" name="" @if(isset($ccomments[1]['status']) && $ccomments[1]['status']) checked @endif></td>
                           <td>@if(isset($ccomments[1]['comment'])){{$ccomments[1]['comment']}}@endif
                              <br>
                              @if(isset($ccomments[1]['files']) && $ccomments[1]['files'])
                              <?php
                                 $ar = json_decode($ccomments[1]['files'],true)
                                 ?>
                              @foreach($ar as $list)
                              <a href="{{ asset('pdf_upload/'.$list) }}"  target="_blank" style="font-size: 20px;"><i class="fa fa-file-pdf-o"></i></a>
                              @endforeach
                              @endif
                           </td>
                        </tr>
                        <tr>
                           <td>Ratenzahlung /Kündige</td>
                           <td><input type="checkbox" name="" @if(isset($ccomments[2]['status']) && $ccomments[2]['status']) checked @endif></td>
                           <td>@if(isset($ccomments[2]['comment'])){{$ccomments[2]['comment']}}@endif
                              <br>
                              @if(isset($ccomments[2]['files']) && $ccomments[2]['files'])
                              <?php
                                 $ar = json_decode($ccomments[2]['files'],true)
                                 ?>
                              @foreach($ar as $list)
                              <a href="{{ asset('pdf_upload/'.$list) }}"  target="_blank" style="font-size: 20px;"><i class="fa fa-file-pdf-o"></i></a>
                              @endforeach
                              @endif
                           </td>
                        </tr>
                        @endif
                     </tbody>
                  </table>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

resources/views/dashboard/optimized/tables/expiring_building_insurance.blade.php
<div class="table-responsive">
   <table class="table table-striped" id="expiring-building-insurance-table">
      <thead>
         <tr>
            <th>Objekt</th>
            <th>AM</th>
            <th>Name</th>
            <th>Kommentare</th>
            <th>Betrag</th>
            <th>Laufzeit</th>
            <th>Kündigungsfrist</th>
            <th>Anzahl</th>
         </tr>
      </thead>
      <tbody>
         @if($data)
            @foreach($data as $list)
               <tr>
                  <td>
                     <a href="{{route('properties.show',['property'=>$list->id])}}?tab=insurance_tab">
                     {{$list->name_of_property}}</a>
                  </td>
                  <?php
                  $subject = 'AUSLAUFENDE GEBÄUDEVERSICHERUNGEN: '.$list->name_of_property;
                  $content = 'Name: '.$list->axa;
               ?>
                  <td>
                     <a href="javascript:void(0);" class="asset_manager" data-property-id="{{ $list->id }}" data-subject="{{ $subject }}" data-content="{{ $content }}" data-title="AUSLAUFENDE GEBÄUDEVERSICHERUNGEN">{{ $list->asset_manager }}</a>
                  </td>
                  <td>{{$list->axa}}</td>
                  <td>{{$list->gebaude_comment}}</td>
                  <td>
                     @if(is_numeric($list->gebaude_betrag))
                     {{number_format($list->gebaude_betrag,2,",",".")}}
                     €
                     @else
                     {{$list->gebaude_betrag}}
                     @endif
                  </td>
                  <td>
                     @if($list->gebaude_laufzeit_to)
                     {{date_format(  date_create(str_replace('.', '-', $list->gebaude_laufzeit_to)) , 'd.m.Y')}}
                     @else
                     {{$list->gebaude_laufzeit_to}}
                     @endif
                  </td>
                  <td>{{$list->gebaude_kundigungsfrist}}</td>
                  <td>
                     <a href="{{route('properties.show',['property'=>$list->id])}}?tab=test_tab">
                     {{$list->insurances($list,1)}}</a>
                  </td>
               </tr>
            @endforeach
         @endif
      </tbody>
   </table>
</div>

resources/views/dashboard/optimized/tables/liquiplanung.blade.php
<div class="row">
	<div class="col-md-12">
		<a href="javascript:void(0);" data-url="{{ route('get_liquiplanung_excel') }}" class="btn btn-success pull-right btn-export">Export</a>
	</div>
</div>
<br>
<div class="row">
	<div class="col-md-12">
		<table id="liquiplanung-table" class="table table-striped">
			<thead>
		     	<tr>
			        <th>#</th>
			        <th>Objekt</th>
			        <th>AM</th>
			        <th>Nettomiete p.m.</th>
			        <th>NK netto p.m.</th>
			        <th>Objektaufwand p.m.</th>
			        <th>Aufwand p.m</th>
			        <th>Außerordentliche Kosten p.m.</th>
			        <th>Kapitaldienst p.m. ann. per 31.12.2019</th>
			        <th>Aktueller Kontostand</th>
			        <th>Datum</th>
			        <th>Cashflow</th>
		     	</tr>
		  	</thead>
			<tbody>
				@if ($data)
					<?php
					$key = 0;
					?>
					@foreach ($data as $value)
						<?php 
							$subject = 'Liquiplanung: '.$value->name_of_property;
							$content = '';

							// if($value->id==3363)
							// 	continue;
						?>
						<tr>
							<td>{{ $key+1 }}</td>
							<?php
							$key += 1;
							?>		
							<td>
								<a href="{{route('properties.show',['property'=> $value->id])}}?tab=finance">{{$value->name_of_property}}</a>
							</td>
							<td>
								<a href="javascript:void(0);" class="asset_manager" data-property-id="{{ $value->id }}" data-subject="{{ $subject }}" data-content="{{ $content }}" data-title="LIQUIPLANUNG">{{ $value->am_name }}</a>
							</td>
							<td class="text-right">{{ show_number($value->nt, 2) }}</td>
							<td class="text-right">{{ show_number($value->nk, 2) }}</td>
							<td class="text-right">{{ show_number($value->object_effort_pm, 2) }}</td>
							<td class="text-right">{{ show_number($value->effort_pm, 2) }}</td>
							<td class="text-right">{{ show_number($value->extra_cost_pm, 2) }}</td>
							<td class="text-right">{{ show_number($value->loan_service_month, 2) }}</td>
							<td class="text-right">{{ show_number($value->current_balance, 2) }}</td>
							<td>{{ ($value->current_balance_updated) ? show_date_format($value->current_balance_updated) : '' }}</td>
							<td class="text-right">
								@if($value->cash_flow > 0 || $value->cash_flow == 0)
									<span style="color: green;">{{ show_number($value->cash_flow, 2) }}</span>
								@else
									<span style="color: red;">{{ show_number($value->cash_flow, 2) }}</span>
								@endif
							</td>
						</tr>
					@endforeach
				@endif
			</tbody>
			<tfoot>
				<tr>
					<th colspan="3" class="text-center">Gesamt</th>
					<th class="text-right">{{ show_number($total_nt, 2) }}</th>
					<th class="text-right">{{ show_number($total_nk, 2) }}</th>
					<th class="text-right">{{ show_number($total_object_effort_pm, 2) }}</th>
					<th class="text-right">{{ show_number($total_effort_pm, 2) }}</th>
					<th class="text-right">{{ show_number($total_extra_cost_pm, 2) }}</th>
					<th class="text-right">{{ show_number($total_loan_service_month, 2) }}</th>
					<th class="text-right">{{ show_number($total_current_balance, 2) }}</th>
					<th></th>
					<th class="text-right">
						@if($cash_flow_total > 0 || $cash_flow_total == 0)
							<span style="color: green;">{{ show_number($cash_flow_total, 2) }}</span>
						@else
							<span style="color: red;">{{ show_number($cash_flow_total, 2) }}</span>
						@endif
					</th>
				</tr>
			</tfoot>
		</table>
	</div>
</div>

resources/views/dashboard/optimized/tables/property_mail.blade.php
<div class="row">
	<div class="col-md-12 table-responsive">
		<table id="property-mail-table" class="table table-striped">
			<thead>
		     	<tr>
			        <th>#</th>
			        <th>Objekt</th>
			        <th>From</th>
			        <th>Name</th>
			        <th>Nachricht</th>
			        <th>Kommentar</th>
			        <th>Datum/Uhrzeit</th>
			        <th>Offen</th>
		     	</tr>
		  	</thead>
			<tbody>
				@if($data)
					@foreach ($data as $key => $value)
						<tr>
							<td>{{ $key+1 }}</td>
							<td>
								<a href="{{route('properties.show',['property'=> $value->property_id])}}?tab=am_mail">{{$value->name_of_property}}</a>
							</td>
							<td>{{ $value->from_name }}</td>
							<td>
								<!--@if($value->type == 5)

									<?php 
										$email_arr = [];
										if($value->custom_email){
											$arr = explode(",", $value->custom_email);
											$arr = array_unique($arr);
											$email_arr = $arr;
										}
									?>
									@if(!empty($email_arr))
										<a href="javascript:void(0);" class="custom_user" data-property-id="{{ $value->property_id }}" data-user-id="" data-subject="{{ $value->subject }}" data-content='{{ $value->message }}' data-title="{{ $value->mail_type }}" data-reload="1" data-email="{{ implode(",", $email_arr) }}">{{ implode(", ", $email_arr) }}</a>
									@endif

								@elseif($value->type == 6)

									<a href="javascript:void(0);" type="button" class="btn-forward-to" data-property-id="{{ $value->property_id }}" data-id="{{ $value->section_id }}" data-subject="{{ $value->subject }}" data-content="" data-title="{{ $value->mail_type }}" data-reload="1" data-email="{{ $value->custom_email }}" data-user="{{ $value->am_id }}">{{ $value->name }}{{ ($value->custom_email) ? ', '.$value->custom_email : '' }}</a>

								@else

									<a href="javascript:void(0);" class="custom_user" data-property-id="{{ $value->property_id }}" data-user-id="{{ $value->am_id }}" data-subject="{{ $value->subject }}" data-content='{{ $value->message }}' data-title="{{ $value->mail_type }}" data-reload="1">{{ $value->name }}</a>

								@endif-->

								@if($value->type == 5)

									<?php 
										$email_arr = [];
										if($value->custom_email){
											$arr = explode(",", $value->custom_email);
											$arr = array_unique($arr);
											$email_arr = $arr;
										}
									?>
									@if(!empty($email_arr))
										{{ implode(", ", $email_arr) }}
									@endif

								@elseif($value->type == 6)

									{{ $value->name }}{{ ($value->custom_email) ? ', '.$value->custom_email : '' }}

								@else

									{{ $value->name }}

								@endif


							</td>
							<td>
								{!! str_replace($value->name_of_property,'',$value->subject) !!}<br>
								{!! $value->message !!}
							</td>
							<td>
								@php
									$comments = DB::table('properties_comments as pc')->select('pc.id','pc.comment', 'u.name', 'pc.created_at', 'u.role', 'u.company')
			                            ->join('users as u', 'u.id', 'pc.user_id')
			                            ->where('pc.record_id', $value->id)
			                            ->where('pc.type', 'send_mail_to_ams')
			                            ->orderBy('pc.created_at', 'desc')
			                            ->limit(2)->get();

			                        $taburl = route('properties.show',['property' => $value->property_id]).'?tab=am_mail';
        							$taburl = "<a href='".$taburl."'>".$taburl."</a>";
								@endphp
								@if($comments && count($comments))
									<div class="show_property_cmnt_section">
										@foreach ($comments as $comment)
											@php
												$company = ($comment->role >= 6 && $comment->company) ? ' ('.$comment->company.')' : '';
                        						$commented_user = $comment->name.''.$company;
											@endphp
											<p><span class="commented_user">{{ $commented_user }}</span>: {{ $comment->comment }} ({{ show_datetime_format($comment->created_at) }})</p>
										@endforeach
									</div>
									<a href="javascript:void(0);" data-url="{{ route('get_property_comment') }}?property_id={{ $value->property_id }}&record_id={{ $value->id }}&type=send_mail_to_ams" class="load_property_comment_section" data-closest="td">Show More</a>
								@endif

								<button type="button" class="btn btn-primary btn-xs btn-show-property-comment" data-form="1" data-record-id="{{ $value->id }}" data-property-id="{{ $value->property_id }}" data-type="send_mail_to_ams" data-subject="{{ $value->subject }}" data-content="{{ $taburl }}">Kommentar</button>
							</td>
							<td>{{ show_datetime_format($value->created_at) }}</td>
							<td>
								<button type="button" class="btn btn-primary mail-mark-as-done" data-url="{{ route('mail_mark_as_done', ['id' => $value->id]) }}">Offen</button>
							</td>
						</tr>
					@endforeach
				@endif
			</tbody>
		</table>
	</div>
</div>

resources/views/dashboard/optimized/tables/standard_land_value.blade.php
<table id="standard-land-value-table" class="table table-striped">
	<thead>
     	<tr>
	        <th>#</th>
	        <th>Objekt</th>
	        <th>AM</th>
	        <th class="text-right">Gebäude</th>
	        <th class="text-right">Grundstück</th>
     	</tr>
  	</thead>
	<tbody>
		@if($data)
			@foreach ($data as $key => $value)
				<tr>
					<td>{{ ($key+1) }}</td>
					<td>
						<a href="{{route('properties.show',['property'=> $value->id])}}?tab=properties">
                        	{{$value->name_of_property}}
                    	</a>
					</td>
					<?php
					$subject = 'GRUND UND BODENRICHTWERT: '.$value->name_of_property;
					$content = "";
					?>
					
					<td>
						<a href="javascript:void(0);" class="asset_manager" data-property-id="{{ $value->id }}" data-subject="{{ $subject }}" data-content="{{ $content }}" data-title="GRUND UND BODENRICHTWERT">{{ $value->asset_manager }}</a>
					</td>
					<td class="text-right">{{number_format($value->building*100,2,",",".")}} %</td>
					<td class="text-right">{{number_format($value->plot_of_land*100,2,",",".")}} %</td>
				</tr>
			@endforeach
		@endif
	</tbody>
</table>